[theme]
# Cor principal (Botões, barras de carregamento e destaques)
primaryColor = "#68a3d3"

# Cor do fundo principal da tela (Azul muito escuro/Noturno)
backgroundColor = "#083749"

# Cor do menu lateral e caixas de texto (Um azul um pouco mais claro que o fundo)
secondaryBackgroundColor = "#083749"

# Cor do texto principal (Branco gelo para dar contraste e não cansar a visão)
textColor = "#ffd902"

# Estilo da fonte
font = "sans serif"